server:
  host: "localhost"
  port: "9999"
  basePath: "/"
  version: "v1.0.0"
  enableSwagger: true # 是否开启 swagger 文档
  globalLimiterMax: 100 # 全局限流器每分钟最大请求数量

log:
  level: -4 # debug -4, Info 0, Warn 4, Error 8
  path: "logs"
